# Generated by Django 3.2.3 on 2021-05-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_id', models.CharField(max_length=200, null=True)),
                ('Area_name', models.CharField(max_length=200, null=True)),
                ('Landmark', models.CharField(max_length=200, null=True)),
                ('Street_name', models.CharField(max_length=200, null=True)),
                ('Lane_no', models.CharField(max_length=200, null=True)),
                ('Pincode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_id', models.CharField(max_length=200, null=True)),
                ('H_name', models.CharField(max_length=200, null=True)),
                ('Total_beds', models.CharField(max_length=200, null=True)),
                ('Shots_per_day', models.CharField(max_length=200, null=True)),
                ('Res_quantity', models.CharField(max_length=200, null=True)),
                ('Availability', models.CharField(max_length=200, null=True)),
                ('Area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.area3')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ind_id', models.CharField(max_length=200, null=True)),
                ('Ind_name', models.CharField(max_length=200, null=True)),
                ('Ind_license', models.CharField(max_length=200, null=True)),
                ('Ind_rating', models.CharField(max_length=200, null=True)),
                ('Area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.area3')),
            ],
        ),
        migrations.CreateModel(
            name='Pharm_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=200, null=True)),
                ('Availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_id', models.CharField(max_length=200, null=True)),
                ('Res_name', models.CharField(max_length=200, null=True)),
                ('cost', models.CharField(max_length=200, null=True)),
                ('Mfg_date', models.DateTimeField(max_length=200, null=True)),
                ('Exp_date', models.DateTimeField(max_length=200, null=True)),
                ('Man_quantity', models.CharField(max_length=200, null=True)),
                ('Ind_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Vac_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_quantity', models.CharField(max_length=200, null=True)),
                ('Availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=200, null=True)),
                ('Res_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='vaccination_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vc_id', models.CharField(max_length=200, null=True)),
                ('Vc_name', models.CharField(max_length=200, null=True)),
                ('Shots_per_day', models.CharField(max_length=200, null=True)),
                ('Area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.area3')),
                ('Vac_res', models.ManyToManyField(to='get_your_resources.Vac_res')),
            ],
        ),
        migrations.CreateModel(
            name='Stockist_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_bought', models.CharField(max_length=200, null=True)),
                ('Availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=200, null=True)),
                ('Res_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stockist_id', models.CharField(max_length=200, null=True)),
                ('S_fname', models.CharField(max_length=200, null=True)),
                ('S_mname', models.CharField(max_length=200, null=True)),
                ('S_lname', models.CharField(max_length=200, null=True)),
                ('Phno', models.CharField(max_length=200, null=True)),
                ('Email_id', models.CharField(max_length=200, null=True)),
                ('Area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.area3')),
                ('Stockist_resource', models.ManyToManyField(to='get_your_resources.Stockist_resource')),
            ],
        ),
        migrations.CreateModel(
            name='Plasma_Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Don_id', models.CharField(max_length=200, null=True)),
                ('Don_name', models.CharField(max_length=200, null=True)),
                ('Don_age', models.CharField(max_length=200, null=True)),
                ('D_ph_no', models.CharField(max_length=200, null=True)),
                ('Blood_group', models.CharField(choices=[('0+', '0+'), ('0-', '0-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+')], max_length=200, null=True)),
                ('Pos_date', models.DateTimeField(max_length=200, null=True)),
                ('Sex', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=200, null=True)),
                ('Hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.CharField(max_length=200, null=True)),
                ('P_name', models.CharField(max_length=200, null=True)),
                ('P_ph_no', models.CharField(max_length=200, null=True)),
                ('Ratings', models.CharField(max_length=200, null=True)),
                ('Area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.area3')),
                ('Pharm_res', models.ManyToManyField(to='get_your_resources.Pharm_res')),
            ],
        ),
        migrations.AddField(
            model_name='pharm_res',
            name='Res_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.resource'),
        ),
        migrations.CreateModel(
            name='Hospital_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_quantity', models.CharField(max_length=200, null=True)),
                ('Availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=200, null=True)),
                ('Res_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.resource')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='Hospital_resource',
            field=models.ManyToManyField(to='get_your_resources.Hospital_resource'),
        ),
    ]
