# Generated by Django 3.2.3 on 2021-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_your_resources', '0003_resource_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='H_ph_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
