# Generated by Django 3.2.3 on 2021-06-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_your_resources', '0005_rename_hospital_resource_hospital_hosres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='Hosres',
        ),
        migrations.AddField(
            model_name='hospital_resource',
            name='H_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='get_your_resources.hospital'),
        ),
    ]
