# Generated by Django 3.2.3 on 2021-06-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_your_resources', '0008_auto_20210602_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='Area_id',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='Area_id',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='stockist',
            old_name='Area_id',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='vaccination_center',
            old_name='Area_id',
            new_name='Area',
        ),
    ]
