# Generated by Django 3.2.3 on 2021-06-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_your_resources', '0009_auto_20210620_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='Area',
            new_name='Area_id',
        ),
        migrations.RenameField(
            model_name='pharmacy',
            old_name='Area',
            new_name='Area_id',
        ),
        migrations.RenameField(
            model_name='vaccination_center',
            old_name='Area',
            new_name='Area_id',
        ),
    ]
